version: "3.3"

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    restart: always
    ports:
      - 5432:5432
    depends_on:
      - redis
    volumes:
      - ./postgres-data:/var/lib/postresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
    - .:/src

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
