version: "3.3"

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postresql
    networks:
      - axe


  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - .:/src
    networks:
      - axe

networks:
  axe:
    driver: bridge